name: Build

on:
  push:
    branches: [ master, setup-builds ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: src/backend
      run: dotnet restore
    - name: Build Debug
      working-directory: src/backend
      run: dotnet build --no-restore
    - name: Test
      working-directory: src/backend
      run: dotnet test --no-build --verbosity normal --settings coverlet.runsettings
    - name: Upload test coverage
      uses: actions/upload-artifact@v2
      with:
        name: backend-coverage
        path: src/backend/Backend.Test/TestResults/**/coverage.info
    - name: Build
      working-directory: src/backend
      run: dotnet build --no-restore Backend/backend.csproj -c Release -o dist
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: backend
        path: src/backend/dist
        retention-days: 1
  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install packages
      run: yarn install
      working-directory: src/frontend
    - name: Run tests
      run: yarn test --coverage
      working-directory: src/frontend
    - name: Upload test coverage
      uses: actions/upload-artifact@v2
      with:
        name: frontend-coverage
        path: src/frontend/coverage/lcov.info
    - name: Build
      run: yarn build
      working-directory: src/frontend
    - name: Upload test coverage
      uses: actions/upload-artifact@v2
      with:
        name: frontend
        path: src/frontend/build
        retention-days: 1
  coverage:
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
    - uses: actions/checkout@v2
    - name: Download Frontend coverage
      uses: actions/download-artifact@v2
      with:
        name: frontend-coverage
    - name: Download Backend coverage
      uses: actions/download-artifact@v2
      with:
        name: backend-coverage
    - name: Check coverage
      uses: codecov/codecov-action@v1
  create-build:
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
    - uses: actions/checkout@v2
    - name: Download backend build
      uses: actions/download-artifact@v2
      with:
        name: backend
        path: build
    - name: Download frontend build
      uses: actions/download-artifact@v2
      with:
        name: frontend
        path: build/frontend
    - name: Upload Build
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build