name: Test and Coverage

on:
  pull_request:
    branches: [ master ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
        working-directory: backend
    - name: Build
      working-directory: backend
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --settings coverlet.runsettings
        working-directory: backend
    - name: Check coverage
      uses: codecov/codecov-action@v1
  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install packages
      run: npm ci
        working-directory: frontend
    - name: Check coverage
      uses: codecov/codecov-action@v1